
const admin = require('firebase-admin');
const serviceAccount = require('./service-account.json');

if (!admin.apps.length) {
    admin.initializeApp({
        credential: admin.credential.cert(serviceAccount)
    });
}

const db = admin.firestore();

async function auditContent() {
    console.log("--- Daily Updates (Last 5) ---");
    const updates = await db.collection('daily_updates')
        .orderBy('publishedAt', 'desc')
        .limit(5)
        .get();

    updates.forEach(doc => {
        const data = doc.data();
        console.log(`ID: ${doc.id}`);
        console.log(`Date: ${data.publishedAt ? data.publishedAt.toDate() : 'N/A'}`);
        console.log(`Title: ${data.title}`);
        console.log(`Source/Type: ${data.source || data.type || 'Unknown'}`);
        console.log(`Image Source: ${data.imageSource}`);
        console.log("--------------------------------");
    });

    console.log("\n--- Drafts (Last 5) ---");
    const drafts = await db.collection('drafts')
        .orderBy('createdAt', 'desc')
        .limit(5)
        .get();

    drafts.forEach(doc => {
        const data = doc.data();
        console.log(`ID: ${doc.id}`);
        console.log(`Created: ${data.createdAt}`);
        console.log(`Generated By: ${data.generatedBy}`);
        console.log(`Status: ${data.status}`);
        console.log("--------------------------------");
    });
}

auditContent().catch(console.error);
